# vim ft=yaml
language: python

env:
  global:
    - DEPENDS="requirements.txt"
    - COVERAGE=0

python:
  - 2.7
  - 3.4
  - 3.5

before_install:
  - source tools/travis_tools.sh
  - virtualenv --python=python venv
  - source venv/bin/activate
  - python --version
  - pip install --upgrade pip
  - wheelhouse_pip_r_install ${DEPENDS}

install:
  - python setup.py install

script:
  - make test

after_success:
  - if [ "${COVERAGE}" == "1" ]; then coveralls; fi
